### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by aksh-github** [shantanuo/sandhi#1]
Hi Shantanu

Akshay Bapaye here. I tried cloning and running the repo in my local. Its not working, can you pls provide support.

Thanks.

**Comment by shantanuo** [comment]
what is the error? Can you send a screen-shot by email? shantanu dot oak at gmail dot com ?

**Comment by aksh-github** [comment]
Hi

I am a Web developer and interested in Sanskrit. I saw your post n repo on
Google groups. I dont have much familiarity with Python. Below are the
details. Thanks.

Getting error on cell 10.

[image: image.png]


Error message:

UnicodeEncodeError                        Traceback (most recent call last)
c:\Users\Akshay\Documents\coding\py\sandhi\sanskrit_sandhi.ipynb Cell 11
line 7
      5 for i in full:
      6     for x in san:
----> 7         print (i, x, i+add, '1.1.1', sandhi_name['1.1.1'])
      8         print (i+add, x, i+add, '1.1.1', sandhi_name['1.1.1'])
     10 for i in half_to_full:

File c:\Python311\Lib\encodings\cp1252.py:19, in
IncrementalEncoder.encode(self, input, final)
     18 def encode(self, input, final=False):
---> 19     return
codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\u0915' in
position 0: character maps to <undefined>

Regards
Akshay B

**Comment by shantanuo** [comment]
I can see the path something like this... "c:\Users\". Are you using windows? If yes, I can not help because I am using Linux. You need to ask on stack-overflow or reddit.

**Comment by shantanuo** [comment]
You can open the script in google colab. Click on this link...

https://colab.research.google.com/

Select "shantanuo" username on GitHub tab. select "sandhi" repo and then click on the link generated for you. It will open the script in google environment.

**Comment by aksh-github** [comment]
Can you provide details what that part of code is doing? Is it something to
do with path / dir concatenation? so based on that I can correct it.

Regards
Akshay B
